name: Eleventy Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assets/*'

jobs:
  write-posts:
    uses: display-pantograph/display-pantograph.github.io/.github/workflows/main.yml@main
  build_deploy:
    needs: write-posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: cjerrington/actions-eleventy@master
        with:
          install_dependencies: true
      - name: optimize-images
        uses: display-pantograph/display-pantograph.github.io/.github/workflows/compress_images.yml@main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
