name: Eleventy Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assets/*'

jobs:
  write-posts:
    uses: display-pantograph/display-pantograph.github.io/.github/workflows/main.yml@main
  build_deploy:
    needs: write-posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
  optimize-images:
    needs: build_deploy
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
