name: Compress Images
on:
  workflow_dispatch:
  workflow_call:

jobs:
  optimize-images:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit compressed images
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          branch: gh-pages
