name: 'Write posts'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assets/'
jobs:
  write-posts:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: cd assets
      - name: Write posts to .md
        run: assets/iterator.sh
        shell: bash
