name: 'Write posts'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assets/*'
jobs:
  write-posts:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Write posts to .md
        run:  (cd assets; ./iterator.sh)
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4        
