name: 'Write posts'

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: macos-13
    steps:
      - name: Write posts to .md
        run: /assets/iterator.sh
        shell: bash
